name: Hello World

on: [push, pull_request]  

jobs:
  hello_job:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@d2 

      - name: Say Hello
        run: echo "Hello World!" 
